use std::io::Write;

use crate::out_fmt::OutFmt;

pub struct TypstSlides<W> {
    writer: W,
}

impl<W> TypstSlides<W> {
    pub fn new(writer: W) -> Self {
        Self { writer }
    }
}

impl<W: Write> OutFmt for TypstSlides<W> {
    fn init(&mut self) -> anyhow::Result<()> {
        writeln!(
            self.writer,
            "// Generated by wohu
#set text(white, 30pt, font: \"Lexend\", weight: 500)
#set page(
    paper: \"presentation-16-9\",
    fill: black,
    footer: context align(right, text(
        rgb(\"#181818\"), 15pt,
        counter(page).display(\"1/1\", both: true)
    ))
)
#pagebreak()"
        )?;
        Ok(())
    }

    fn write_verse(&mut self, verse: &[String]) -> anyhow::Result<()> {
        writeln!(self.writer, "#align(center + horizon)[")?;
        for v in verse {
            writeln!(self.writer, "    {v} \\")?;
        }
        writeln!(self.writer, "]\n#pagebreak()")?;
        Ok(())
    }

    fn song_space(&mut self) -> anyhow::Result<()> {
        writeln!(self.writer, "#pagebreak()")?;
        Ok(())
    }

    fn verse_space(&mut self) -> anyhow::Result<()> {
        writeln!(self.writer)?;
        Ok(())
    }

    fn finalize(&mut self) -> anyhow::Result<()> {
        Ok(())
    }
}
